### ISSUE TITLE
stack-ide-sublime cannot find any files

### ISSUE THREAD

**Issue by rubenmoor** [lukexi/stack-ide-sublime#12] opened 2015-08-25 09:16 UTC
I get this console output

```
[SublimeStackIDE][DEBUG]: Got response:  {'tag': 'ResponseGetSourceErrors', 'seq': '9a5a8223-e3a6-48c3-afd8-1bc0ee8809ce', 'contents': [{'errorKind': 'KindError', 'errorSpan': {'tag': 'TextSpan', 'contents': '<no location info>'}, 'errorMsg': "can't find file: /home/ruben/code/holger/core/DPM.Utils"}, ...
```

which goes on for every single file/module in my project. And followed by some lines that go like

```
[SublimeStackIDE][WARN]: Unhandled error tag type:  {'tag': 'TextSpan', 'contents': '<no location info>'}
```

Running `stack ide start` on my command line does not seem to complain about anything:

```
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /home/ruben/.local/bin/ide-backend-server @(ideba_6Lk4KkgBBPc3oGkkTS3Fy7:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_6Lk4KkgBBPc3oGkkTS3Fy7:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:223:5)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusDone","contents":[]}}
```

**Comment by jcpetruzza** [comment] 2015-08-25 09:26
Can you reproduce the problem from the command line if you add the name of the containing folder to the `stack ide start` command, which corresponds to what the plugin currently does? E.g., if you are running it from `/home/ruben/code/holger`, that should be `stack ide start holger`, etc

**Comment by rubenmoor** [comment] 2015-08-25 10:18
I ran `stack ide start core` in my project directory, `core` being the name of my project as in `core.cabal`, and it did not reproduce the behaviour of stack-ide-sublime.

**Comment by jcpetruzza** [comment] 2015-08-25 19:44
Ok, could you try running again `stack ide start core` and then paste this through stdin?

```
{"tag": "RequestGetSourceErrors", "contents": []}
```

The error came in a "response" to a `GetSourceErrors` request, so we need to send that to `stack-ide` as well in order to trigger it.

_Edit_: fixed the instructions

**Comment by rubenmoor** [comment] 2015-08-26 09:13
```
echo '{"tag": "RequestGetSourceErrors", "contents": []}' | stack ide start core
```

The above line indeed lead to reproducing my stack-ide-sublime behavior, i.e. for every single file the following error message:

```
{"tag":"ResponseGetSourceErrors","contents":[{"errorSpan":{"tag":"TextSpan","contents":"<no location info>"},"errorKind":"KindError","errorMsg":"can't find file: /home/ruben/code/holger/core/DPM.Utils"}, ...
```

**Comment by jcpetruzza** [comment] 2015-08-26 09:30
Ok, this seems to be a problem in `stack-ide`. What appears to be going on is that it is using the name of a module (namely, `DPM.Utils`) where a file name is expected. I have no idea why, but this is consistent with what was reported in #13, so you are not alone with this.

**Comment by jcpetruzza** [comment] 2015-08-26 09:35
Users of `stack-mode` are seeing the same problem (https://github.com/commercialhaskell/stack-ide/issues/56), so this is definitely a `stack-ide` issue

**Comment by jcpetruzza** [comment] 2015-08-26 09:44
Duplicate of #13

**Closed as completed by jcpetruzza** 2015-08-26 09:44 UTC
